server:
  port: 8096
spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: config-service
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
